In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:99% !important;}
div.cell.code_cell.rendered{width:90%;}
div.CodeMirror {font-family:Consolas; font-size:18pt;}
div.output {font-size:19pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:19pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
span.toc-item-num{display:none;}
div.text_cell_render ul li{font-size:16pt;padding:5px;}
div.CodeMirror-lines > div {padding-left:10px;}
table.dataframe{font-size:13px;}
</style>
"""))

<b><font color="red" size="6">ch11. N차원 배열 다루기</font></b>
- [numpy](https://numpy.org/)
- [numpy docs](https://numpy.org/doc/stable/)
- N차원 배열 객체
- 2차원 배열은 행렬개념으로 이해
- numpy 패키지를 이용(C언어로 구현된 고성능 수치계산 패키지)

# 1절. 넘파이 패키지

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
a = np.arange(15) # 0부터 15앞까지 1씩 증가하는 1차원 배열
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
from numpy import arange
a = arange(15).reshape(3,5) # 3행5열짜리 2차원 배열
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
type(a) # a배열 변수의 타입

numpy.ndarray

In [6]:
a.dtype # a배열변수의 요소들의 type

dtype('int32')

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize # 한 요소의 bytesize (int32의 경우 : 4byte)

4

In [9]:
a.ndim # 축수(차원수)

2

In [10]:
a.size # 배열 요소의 갯수

15

In [11]:
a.shape # 배열의 구조(3행5열)

(3, 5)

In [12]:
print('shape 조정 전 a:\n', a)
a.shape = (5,3)
print('shape 수정 후 a :\n', a)

shape 조정 전 a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape 수정 후 a :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [14]:
# 배열 요소의 타입을 수정
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a.size # 요소의 갯수

12

In [18]:
a.dtype

dtype('int32')

In [19]:
a.itemsize

4

In [20]:
a.dtype = np.int64
a.dtype

dtype('int64')

In [22]:
a.itemsize # 요소의 byte 사이즈

8

In [23]:
a.size

6

In [24]:
a

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)

In [25]:
a.ravel() # flatten 됨()

array([ 4294967296, 12884901890, 21474836484, 30064771078, 38654705672,
       47244640266], dtype=int64)

# 2절. 넘파이 배열
- array()함수를 이용한 다른 파이썬 구조(list, tuple)를 배열로 변환
- 기타 함수들 : arange, ones, zeros, empty
- 랜덤값을 갖는 함수들 ....
- [넘파이 doc](https://numpy.org/doc/stable/)
- [넘파이 함수들](https://numpy.org/doc/stable/reference/index.html#reference)

## 2.1 array()함수로 넘파이 배열 만들기
- array(obj, dtype=np.xx, copy=T/F)

In [30]:
a = np.array([2, 4, 6], dtype=np.int16) # 정수의 기본타입 int32
a

array([2, 4, 6], dtype=int16)

In [32]:
a[0], a[1], a[2]

(2, 4, 6)

In [33]:
for i in a:
    print(i, end='\t')

2	4	6	

In [34]:
a.dtype

dtype('int16')

In [40]:
b = np.array([[1.5, 2.3],  # 실수의 기본 타입은 float64
              [4,5]])      # 동일 자료형으로 배열 생성 : 정수>실수>문자
b

array([[1.5, 2.3],
       [4. , 5. ]])

In [37]:
b[0][0], b[0,0] # 2차원 [axis0행, axis1열]

(1.5, 1.5)

In [42]:
b = np.array([(1.5, 2.3),  # 실수의 기본 타입은 float64
              (4,5)])      # 동일 자료형으로 배열 생성 : 정수>실수>문자
b

array([[1.5, 2.3],
       [4. , 5. ]])

In [43]:
a = np.array([[1.5, 2.3], [4,5]]).reshape(1,4) # 2행2열짜리 배열을 1행 4열로 shape 변환
a

array([[1.5, 2.3, 4. , 5. ]])

In [44]:
a.dtype

dtype('float64')

In [46]:
a = np.array([1.5, 2.3, 4,5], dtype=np.float32).reshape(2,2)
a

array([[1.5, 2.3],
       [4. , 5. ]], dtype=float32)

In [47]:
a.itemsize # 한 요소의 byte 수

4

In [49]:
a.dtype

dtype('float32')

In [52]:
# a.dtype = np.float64 안 됨
a = a.astype(np.float64) # 배열 요소의 타입을 바꾸는 함수
a

array([[1.5       , 2.29999995],
       [4.        , 5.        ]])

In [54]:
a.dtype

dtype('float64')

In [55]:
l = [[1, 2], [3.4, 4.5]]
for row in l:
    for data in row:
        print(data, end='\t')
    print()

1	2	
3.4	4.5	


In [56]:
for i, row in enumerate(l):
    for j, data in enumerate(row):
        print("{}행{}열 : {}".format(i, j, data), end='\t')
    print()

0행0열 : 1	0행1열 : 2	
1행0열 : 3.4	1행1열 : 4.5	


In [58]:
l[0][0]

1